apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app: payment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: 340752807675.dkr.ecr.us-east-1.amazonaws.com/spinz3-payment-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          value: "postgres://jwillz:cirfof-wimvoc-bAbhu3@spinz-prod-db.cleardb.net:5432/spinz_db"
        - name: S3_BUCKET
          value: "spinz-app-assets"
        - name: AWS_REGION
          value: "us-east-2"
        - name: STRIPE_SECRET_KEY
          value: "your-stripe-secret-key"  # Replace with your actual Stripe secret key
